# Sane tmux defaults
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Better prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Quality of life
set -g history-limit 10000
set -g status-interval 5
set -g default-terminal "screen-256color"
